In [1]:
import numpy as np

In [3]:
## creation of array 1D 
arr = np.array([25,41,63,66,85,74])
arr 

array([25, 41, 63, 66, 85, 74])

In [4]:
type(arr)
# ndarray  ==> n diminensional array 

numpy.ndarray

In [5]:
arr.size  # no. of  item 

6

In [6]:
len(arr)

6

In [7]:
arr.ndim   # to check the dimension of array 

1

In [23]:
arr = np.array([25,41,63,66,85,74,25.01,'upflairs',True])
arr 
## similar type store  
## array similar item 

array(['25', '41', '63', '66', '85', '74', '25.01', 'upflairs', 'True'],
      dtype='<U32')

In [21]:
arr.dtype

dtype('float64')

In [17]:
print(np.__version__)

1.26.0


In [37]:
ls = [25,41,63,66,85,74]
arr = np.array(ls)
arr 

array([25, 41, 63, 66, 85, 74])

In [25]:
arr[-1]

74

In [29]:
arr[::] # start = 0  , stoping  = end , jump == 1 

array([25, 41, 63, 66, 85, 74])

In [32]:
arr[-1] = 500

In [33]:
arr

array([ 25,  41,  63,  66,  85, 500])

In [35]:
arr + 2

array([ 27,  43,  65,  68,  87, 502])

In [36]:
arr * 2


array([  50,   82,  126,  132,  170, 1000])

### 2D arrays  

In [3]:
ls = [[1,2,3],
     [4,5,6],
     [7,8,9]]

ls 

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [39]:
type(ls)

list

In [43]:
ls[-1]

[7, 8, 9]

In [4]:
arr2 = np.array(ls)
arr2 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
# 9  = 90  
arr2[-1,-1] = 90 

In [7]:
arr2 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 90]])

In [8]:
arr = np.random.randint(1,200,500)
arr # single dimension array 
# 1 bag of marbles 10 pick 

array([ 48, 196, 145,  98,  11,  36,  78,  10,  76,  66, 191,  50,  58,
       176, 179,  10, 158, 146, 155,  35, 173,  59,  56,  41,  68,  13,
        87, 159, 143,  25,  59,  51, 100,   4,  71,  87, 114, 128, 136,
        33, 119, 114,  37,  52,  43,  15,  64, 193,  15, 141,  45,  24,
       172,  26,   5,   9,  71, 174,  40, 178,   1,  21,  24, 147, 117,
        15,  69,  88,   1, 138, 117, 107, 158,  91,   5, 101,   8, 115,
       128,   8, 197,  42,  75, 188,  11,  50, 178,  49, 112,  75, 142,
       151, 108, 164,  81, 141, 132, 117, 151, 161, 132, 141, 141,  31,
       164, 117,  79,  88,  38, 147, 197,  73, 175,  60,  22, 135,   5,
        40,  43,  24,   1, 149, 121, 178,  61,  30, 158,  25, 112, 124,
        11,  87, 197, 133, 177, 107, 195,  73,  71, 136,  24, 107,  91,
        38, 119, 179,  76,  74, 192,  73,  85, 100, 141, 173,  38,   3,
       186,  67, 128, 134, 101,  89, 131, 114,  39,   4, 102, 115, 135,
       183,  14, 169,  67, 175,  97,   4,  51,  20,  96, 101, 12

In [11]:
# arr  filter all thos item that are less than equal to 100  
# comments ---> how many item in your arrays 

arr[arr <= 100]

array([ 48,  98,  11,  36,  78,  10,  76,  66,  50,  58,  10,  35,  59,
        56,  41,  68,  13,  87,  25,  59,  51, 100,   4,  71,  87,  33,
        37,  52,  43,  15,  64,  15,  45,  24,  26,   5,   9,  71,  40,
         1,  21,  24,  15,  69,  88,   1,  91,   5,   8,   8,  42,  75,
        11,  50,  49,  75,  81,  31,  79,  88,  38,  73,  60,  22,   5,
        40,  43,  24,   1,  61,  30,  25,  11,  87,  73,  71,  24,  91,
        38,  76,  74,  73,  85, 100,  38,   3,  67,  89,  39,   4,  14,
        67,  97,   4,  51,  20,  96,   8,  15,  98,  83, 100,  14,  96,
        58,  92,  53,  93,  82,  64,  14,  66,  21,  87,  91,  14,  66,
        55,  93,  79,  22,  80,  63,  82,  78,  44,  57,  97,  60,  48,
        91,  61,  61,   4,  83,  20,  12,  38,  60,  95,   9,  79,  21,
        30,  93,  76,  71,  56,  34,  46,   9,  66,  12,  32,  43,  76,
        60,  85,  63,   9,  36,  72,  15,   3,   7,  68,  16,  65,  69,
        27,  18,  78,  92,  37,  14,  49,  24,  19,  91,  94,  5

In [12]:
arr[arr <= 100].size

268

In [13]:
len(arr[arr <= 100])


268

In [14]:
arr[arr <= 100].shape  


(268,)

In [17]:
arr2 = np.random.randint(1,200,(10,5))
arr2 

array([[ 97, 179,  80,  62,  39],
       [102,  54, 122,  51,   5],
       [ 21, 169, 139,  47,  52],
       [ 97,  32,  32,  83, 173],
       [ 89, 173, 174,  65, 141],
       [171, 111, 167, 164,   5],
       [146,  57,  21, 169, 174],
       [115, 195,  23,  14, 136],
       [ 68,  96, 145,  66, 150],
       [139, 178, 163, 188, 140]])

In [23]:
arr2 = np.random.randint(1,200,(10,6))
arr2 

array([[123,  64, 128,  10, 137, 153],
       [ 89,  76, 142, 150,  77,  26],
       [111,  31,  55,  59, 109,  75],
       [ 55,   5, 106, 141, 150, 126],
       [127, 158,   7,  57,  71, 171],
       [ 94, 122, 128, 144,  73,  63],
       [ 13,  41,   7,  14,  61, 116],
       [162,  22, 109, 144, 107,   3],
       [141, 123, 117,  75, 163, 180],
       [ 71, 174,  20,  26,  80, 141]])

In [24]:
arr = np.zeros(10)
arr # 1D array 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
arr.dtype

dtype('float64')

In [27]:
arr = np.zeros((10,5))  # 2D array 
arr 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
arr = np.ones(10)
arr 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
arr = np.ones((10,5))
arr 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
ls = [0,1,2,3,4,5,6,7,8,9]
ls 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
ls = list(range(10))
ls 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
arr = np.arange(10)
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr = np.arange(60)
arr  # single 1D 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [44]:
# 2D , 60
# 10,6
arr.reshape(6,10)  # 10 *  6 == 60 

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [47]:
arr.reshape(3,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59]])

In [48]:
arr = arr.reshape(6,10)  # 10 *  6 == 60 

In [49]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [ ]:
# message = s.recvfrom(100)
# sender_address = message[1]
# reply_message = "Thank you for sending message "
# encryptmessage  = ......... 
# s.sendto(encryptmessage,sender_address)


In [2]:
### creation of 3D array
arr1D = [1,2,3]
arr2D = [[1,2,3],[1,2,3],[1,2,3]]  # [1D,1D,1D]
arr3D = [[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]]     # [2D,2D,2D,2D]

In [3]:
arr = np.array(arr3D)
arr 

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [4]:
arr.ndim

3

In [6]:
arr3 = np.random.randint(1,200,(3,5,3))
arr3 
# (10,5)  (row,column)

array([[[ 86, 125,  70],
        [ 69,  49,  59],
        [ 72,  10,  36],
        [171, 160,  56],
        [ 50,  46,  78]],

       [[ 70, 177,   6],
        [ 83,  87,  83],
        [117, 107,  94],
        [146,  11,  47],
        [ 63,  94,  73]],

       [[187, 104, 190],
        [ 55,  35, 187],
        [105,  31, 148],
        [ 21, 198, 164],
        [106, 187,  23]]])

In [8]:
arr3.shape 
#(table,  row , column)

(3, 5, 3)

In [10]:
arr3.ndim 

3

In [13]:
arr3[0:,0,:]   

array([[ 86, 125,  70],
       [ 70, 177,   6],
       [187, 104, 190]])

In [15]:
arr = np.array([9,7,8])
arr 

array([9, 7, 8])

In [20]:
# max(arr)   # min(arr)

In [19]:
np.mean(arr)   # average 

8.0

In [21]:
np.sum(arr)

24

In [24]:
np.argmin(arr)
# argmin returns index of minimum item 

1

In [25]:
np.argmax(arr)

0

In [27]:
arr.sort()  # ascending order 

In [30]:
arr  # ascending order 

array([7, 8, 9])

In [ ]:
arr[::-1]   # descending order 

